### ISSUE TITLE
Issues with `level-party`

### ISSUE THREAD

**Issue by jcrugzz** [mafintosh/subleveldown#3]
Seems like a subtle incompatibility with what I'm doing [here](https://gist.github.com/jcrugzz/cd2eb5aa5a69080fe6f6). As a note `level-party-hyper` is just a direct fork that uses `level-hyper` rather than `level-prebuilt` so I can compile it on CENTOS (unfortunate need).

**Comment by mafintosh** [comment]
Fixed in latest level-party
