### ISSUE TITLE
Question: how to do batch() across multiple sublevels?

### ISSUE THREAD

**Issue by tgohn** [mafintosh/subleveldown#4]
Hi,

My apologies if this has been answered before.

If I want to batch operations across multiple sublevels, do I have to construct the operations using `sublevel.db.prefix` property?

```javascript
root_levelup.batch([
  {type: 'put', 'key': sub1.db.prefix + 'key', value: 'val'},
  {type: 'put', 'key': sub2.db.prefix + 'key', value: 'val'}
]);
```

Or is there already some utils function to do this? :sweat_smile:

**Comment by mafintosh** [comment]
I use this to do it, https://github.com/mafintosh/sublevel-prefixer and then i just use the toplevel db.

**Comment by tgohn** [comment]
Thanks for the reply.

From the code, it looks like `sublevel-prefixer` is not meant to use with nested sublevels.
Because a subleveldown prefix would be in this format `sub2.db.prefix === "!sub1!!sub2!"`

Just curious, is nested sublevels not a favorable choice?

**Comment by mafintosh** [comment]
You can calls to sublevel-prefixer

**Comment by mafintosh** [comment]
* You can do subsequent calls to sublevel-prefixer

``` js
var prefix = prefixer()
prefix('hello', prefix('world', 'stuff')) // !hello!!world!stuff
```

**Comment by tgohn** [comment]
ah, I see, didnt think of using the prefixer like that.
Thanks a lot @mafintosh  :smile:

**Comment by mvayngrib** [comment]
@mafintosh how would you preserve the correct encodings on members of the batch (assuming they're different from each other or from the top level)?

**Comment by tounano** [comment]
@mvayngrib here is what I do.

I always use binary encoding. So whatever I save, I save in binary. For the first week I started doing that it was a headache, but it was bigger headache to work the other way :)

**Comment by CMCDragonkai** [comment]
So the default separator used in subleveldown is `!`.

Therefore to acquire the prefix:

```
var prefix = prefixer('!')

const k = prefix('permissions', 'my-key'); // !my-prefix!my-key

const db = await level();

const permDb = sub(
  db,
  'permissions',
);

db.get(k);
```

Does that mean `k` will access the the `my-key` from `permDb`?
