### ISSUE TITLE
Omitting `prefix`?

### ISSUE THREAD

**Issue by paulkernfeld** [mafintosh/subleveldown#5]
Omitting `prefix` is equivalent to passing in the empty string for the prefix, which seems like it defeats the point of using subleveldown. Is there a use case for omitting prefix, or could we make it a required argument (for which the user can still pass in an empty string)?

**Comment by paulkernfeld** [comment]
For reference, the dumb thing that I did was to forget to add a prefix, and then be surprised when all my databases were the same!

**Comment by mafintosh** [comment]
The empty prefix gets translated to `!!` which is still a prefix. In general you use the empty prefix for your main database. This is to mimick the same behaivor of the original sublevel module

**Comment by paulkernfeld** [comment]
Oh okay, that makes sense!
